version: '3'
services:
    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "3000:3000"
        depends_on:
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        volumes:
            - ./rabbitmq:/etc/rabbitmq/
            - ./rabbitmq:/var/lib/rabbitmq/
            - ./rabbitmq:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
        #command: rabbitmq-plugins enable --offline rabbitmq_management